### ISSUE TITLE
Module settings remain unchanged if admin page name is changed

### ISSUE THREAD

**Issue by theoretic** [outflux3/SettingsFactory#9]
Let's suppose we've created an admin page named my-settings-01. A section "my-settings-01" will appear in SettingsFactory module config data. If we later rename our admin page to my-settings-02, the "my-settings-01" config section will keep its name, however it should be changed to "my-settings-02".

**Comment by outflux3** [comment]
The module keys each settings page off the page name, so that when you want to get your settings, you can refer to them by name in your code and making the code more readable and easier to grasp which settings you are using in any given area.

So it was decided to not key the settings to the page id. Therefore as the module currently exists, if you change the name of your settings page, then you need to update all places that you refer to the settings, because the module will see the changed page as a whole new set of settings.

And because of the way that module config data is stored, once a key is stored in the config, it will persist, unless you delete it from the database.

That's how i think this works, but if you see some error in what i have explained above, let me know.

**Comment by theoretic** [comment]
Thanks for very detailed reply! I think You can close the issue.
